[tool.black]
line-length = 120
exclude = '''
^/(
  (
    | .git
    | env
    | venv
    | alembic
    | migrations
  )/
  | tox.ini
  | .gitignore
)
'''
[tool.isort]
profile = "black"
skip = ["env", "venv", ".gitignore", "migrations"]
